# Generated by Django 3.2.3 on 2021-05-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='show_comment',
            field=models.BooleanField(default=False),
        ),
    ]
