# Generated by Django 3.2.3 on 2021-05-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210526_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopRated',
        ),
    ]
